# Generated by Django 4.1.4 on 2022-12-25 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_images_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
