# Generated by Django 4.1.4 on 2022-12-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='aboutus',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='setting',
            name='references',
            field=models.TextField(max_length=50),
        ),
    ]
