# Generated by Django 4.1.4 on 2022-12-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contactformmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(default='', max_length=200)),
                ('subTitle', models.CharField(max_length=200)),
                ('product_Image', models.ImageField(null=True, upload_to='uploads')),
                ('see_on_slider', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('category_of_the_month', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('featured_product', models.BooleanField(default=False)),
            ],
        ),
    ]
