# Generated by Django 4.1.4 on 2022-12-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_homeslider_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('eMail', models.CharField(max_length=100, null=True)),
                ('subject', models.CharField(max_length=200, null=True)),
                ('message', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
